### ISSUE TITLE
data generation problem - seems no progress

### ISSUE THREAD

**Issue by waldstein94** [shunsukesaito/PIFu#26]
In advance, thank you for your amazing works and I'm very enjoying it!

Here's problem: when I ran the 'prt_util.py' file, I found there seemed no progress in the progress bar in console and only my CPU was used 100%. (I set up all the libraries you noted.) Also, you wrote "Warning: the following code becomes extremely slow without pyembree.", however, I couldn't find any usage of pyembree library in the entire project. 

I don't know what's the next step. If you have a any idea about my problem, give me a comment!

**Comment by shunsukesaito** [comment]
Glad to hear that you like PIFu :) 

>only my CPU was used 100%
How many threads are used with 100%? As pyembree utilize multithreading, you would likely see 100% from most of threads. If that's the case, probably pyembree is already being used. Otherwise, you need to install pyembree together with trimesh. 

>I couldn't find any usage of pyembree library in the entire project.
Pyembree is required for computing ray intersection inside trimesh (https://trimsh.org/). So it does not appear in my own dependencies.

**Comment by waldstein94** [comment]
After uninstalling and re-installing trimesh and pyembree, the code began working well. There might be some problems when I installed two packages at first.

Thank you for your help!!

**Comment by shunsukesaito** [comment]
Awesome!
