### ISSUE TITLE
Query regarding Sigma

### ISSUE THREAD

**Issue by jsaisagar** [shunsukesaito/PIFu#54]
Hi,

I have my models scaled to unit box in meshlab. I have trained this data with sigma=5 in which i observed no change in the error. I have trained the same data with sigma 0.1 where I observed error decreasing.
However, marching cubes error still persists even after 15th epoch. May I know if any changes to code should be incorporated from changing meshes to unit box? 

Thanks,

**Comment by shunsukesaito** [comment]
In the paper, the sigma was in cm unit. If you rescale the objects, you need to adjust the sigma accordingly. Dumping out the sampled points after normalization as PLY or OBJ files and previewing it via meshlab is highly recommended.

**Comment by jsaisagar** [comment]
Hi,

The ply is as below. May if everything is in place?
<img width="454" alt="Screenshot 2020-07-22 at 8 32 51 AM" src="https://user-images.githubusercontent.com/6646353/88129641-359b8780-cbf6-11ea-98ba-fb48edac695d.png">

**Comment by shunsukesaito** [comment]
You can load the normalized mesh file in the same viewer to see if the points are nicely distributed around the surface. If not, likely, you set sigma too big.

**Comment by jsaisagar** [comment]
Thanks for the reply. It worked by tweaking TrainDataset.py. Also, subtracting vertices with trimesh's mesh.center_mass also helps.

**Comment by ujjawalcse** [comment]
Hi @jsaisagar , 
How did you tweak the TrainDataset.py?
I'm also getting marching cube error and the error value is 0.0000 if the sigma is 5. But when i used sigma=0.5, I'm getting error value 0.01. But I'm still getting marching cube error.
As @shunsukesaito said,how to dump sampled points after normalization so that i can open in meshlab and get some insight?
Please feel free to discuss.
Thanks.
