### ISSUE TITLE
Obj files requirement 

### ISSUE THREAD

**Issue by yehDilBeparwah** [shunsukesaito/PIFu#62]
Hi @shunsukesaito 

Could you list the requirements on input obj files?
Some that I have picked from the code (requirement for a texture file, [water-tight meshes](https://github.com/shunsukesaito/PIFu/issues/30))
I am looking to assemble a dataset for facial digitization.

Goes without saying, great work done.

**Comment by yehDilBeparwah** [comment]
Also, what do the files at the end of render_data.py represent.

 ```
    os.makedirs(os.path.join(out_path, 'PARAM', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'RENDER', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'MASK', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'UV_RENDER', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'UV_MASK', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'UV_POS', subject_name),exist_ok=True)
    os.makedirs(os.path.join(out_path, 'UV_NORMAL', subject_name),exist_ok=True)
```
Q. In essence what I am trying to understand is which of these files represents the depth and the signed distance
of a pt, from this eqn.
f(F(x),z(X)) = s : s ∈ R,(1) from the paper.

**Comment by shunsukesaito** [comment]
>Could you list the requirements on input obj files?

If you want to render images with my code, obj files need to have uv maps and texture data on the texture map. But feel free to make modification in the code to support your needs (e.g., using per-vertex color instead of texture mapping etc). 

> Q. In essence what I am trying to understand is which of these files represents the depth and the signed distance
of a pt, from this eqn.

None of the folders above stores occupancy labels. These labels are computed on the fly in this line https://github.com/shunsukesaito/PIFu/blob/30b428ba74bd7743a17c19fa20f6bfd39b1de057/lib/data/TrainDataset.py#L262
