### ISSUE TITLE
Perspective Projection

### ISSUE THREAD

**Issue by sxyu** [shunsukesaito/PIFu#68]
Hi Shunsuke,

Thanks for answering my questions previously.
I am wondering, what is the technical reason all PIFu/pifuhd models use weak-perspective projection? Does it make the model work better due pixel alignment, or is it out of simplicity/efficiency?

In particular, I wonder if you have tried using perspective and if the released PRT renderer supports it.

Thanks,
Alex

**Comment by shunsukesaito** [comment]
Hi thanks for the question. Indeed PIFu/PIFuHD all use weak-perspective. The reason is two fold:
- With weak perspective, image-space augmentations (random translation, rotation, scaling etc) are a lot easier to implement.

- In weak perspective, depth center can be arbitrarily set, meaning for example, we can ensure the pelvis centers are aligned across data samples no matter how big the subject is. With perspective model, scale and z-translation is interchangeable, causing the depth center to be not normalized anymore. 

Hope this helps. Let me know if you have further questions.

**Comment by sxyu** [comment]
Thank you for the answer, that is what I suspected. For multi-view / video PIFu on real images one might need to use perspective however.
