### ISSUE TITLE
Partial views

### ISSUE THREAD

**Issue by faniry6** [shunsukesaito/PIFu#71]
Hi Shunsuke

In our training datasets, we have views where only a part of the object appear. This may cause problems since the prediction might be then wrong especially at the stage where you use 

``in_img = (xy[:, 0] >= -1.0) & (xy[:, 0] <= 1.0) & (xy[:, 1] >= -1.0) & (xy[:, 1] <= 1.0)`` in ``HGPIFuNet.py`` 

A  point can be inside the geometry even though it is not seen in the current view. 

- Do you have an idea on how could these cases be handled? 
- Also  is there some reason why the coordinates are in [-1, 1] not in pixel? 

Thanks in advance

**Comment by shunsukesaito** [comment]
This is after normalizing pixel coordinates to [-1, 1]. PIFu is reasoning 3D shapes from corresponding pixel-aligned features, meaning it's not possible to make any prediction for outside image plane. The reason why the value is ranged in [-1, 1] is because this is the expected value for F.grid_sample.
